# Generated by Django 5.2.1 on 2025-09-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50, null=True)),
                ('rank', models.CharField(max_length=50, null=True)),
                ('ifo', models.CharField(max_length=5000, null=True)),
                ('advantage', models.CharField(max_length=5000, null=True)),
            ],
        ),
    ]
