# Generated by Django 5.2.1 on 2025-09-02 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=11, unique=True)),
                ('passwd', models.CharField(max_length=32)),
                ('avatar', models.CharField(max_length=500, null=True)),
                ('call_name', models.DateTimeField(auto_now_add=True)),
                ('last_login_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
