# Generated by Django 5.2.1 on 2025-08-31 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat', '0002_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='summary',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
