# Generated by Django 5.2.1 on 2025-08-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('user_id', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
