# Generated by Django 5.2.1 on 2025-09-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat', '0003_topic_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
