# Generated by Django 5.2.1 on 2025-09-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat', '0004_topic_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
