"""
Django settings for aiserver project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-g0%9j&n&9egjn+w=2jtbyyy$*8*v6e9ifi30ae+n=f*jz!tsuc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.6.179','127.0.0.1','localhost']
# 在 settings.py 中添加
# CORS_ALLOWED_ORIGINS = [
#     "http://192.168.6.179:5173",  # uni-app 开发服务器地址
#     "http://localhost:5173",
#     "http://127.0.0.1:5173",
# ]
CORS_ALLOW_ALL_ORIGINS = True
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'corsheaders',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'aichat.apps.AichatConfig',
    "user.apps.UserConfig",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_CREDENTIALS = True
ROOT_URLCONF = 'aiserver.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aiserver.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'llmserver',           # 替换为你的数据库名
        'USER': 'root',           # 替换为你的数据库用户名
        'PASSWORD': 'root',   # 替换为你的数据库密码
        'HOST': '127.0.0.1',                    # 替换为你的数据库主机地址
        'PORT': '3306',                         # MySQL默认端口
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# 静态文件路径
STATICFILES_DIRS = [os.path.join(BASE_DIR,"static")]
# STATIC_ROOT = [
#     BASE_DIR / "static",
# ]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# vLLM配置信息
VLLM_CONFIG = {
    "host" : "http://172.23.241.16:8000",
    "model" : "/data/huggingface/deepseek-1.5B",
}

# # vLLM配置信息
# VLLM_CONFIG = {
#     "host" : "http://192.168.6.179:8000",
#     "model" : "/data/huggingface/deepseek-1.5B",
# }

# RAG配置信息
RAG_CONFIG = {
    "chunks_path" : os.path.join(BASE_DIR,"chunks","medical_dialog.json"),
    "chroma_host" : {"host":"192.168.6.179",
                     "port": 8002,
                     },
    "chroma_config":{
        "embedding_model_path": "D:/PythonModel/huggingface/bge-base-zh-v1.5",
        "collection_name": "my-collection-decimal"
    },
    "rerank_host" : "http://172.23.241.16:8001/rerank",   #这个没问题
    "rerank_model" : "/data/huggingface/bge-reranker-base",
    "rerank_threshold" : 0.7,
    "rerank_top_k":5,
}
